spring:
  application:
    name: paceline

paceline:
  device:
    mdns-service-type: _wahoo-fitness-tnp._tcp.local.
    discovery-timeout: 5s
    connect-timeout: 3s
    protocol-timeout: 3s
  intervals:
    base-url: https://intervals.icu
